output "generated_files" {
  value       = [for name in sort(keys(local_file.generated_files)) : local_file.generated_files[name].filename]
  description = "Paths of files generated by the shared root generator."
}
